### ISSUE TITLE
获取版本号失败

### ISSUE THREAD

**Issue by earthjasonlin** [HuanLinOTO/GenshinCloudGameHelper#1]
如图，但如果手动把版本号改成3.2就可以正常签到
![图片](https://user-images.githubusercontent.com/83632110/202897569-d624ff31-4343-477d-9bc3-ee252774d4ee.png)

**Comment by HuanLinOTO** [comment]
我在写这玩意的时候测试到他给了两个版本号（versions）
你可以尝试把appversion.data.config打印出来 让我看看
tip：云原神的版本和原神版本不一样的 小心黑号



在 2022-11-20 18:39:25，"Zichao Lin" ***@***.***> 写道：

如图，但如果手动把版本号改成3.2就可以正常签到

**Comment by earthjasonlin** [comment]
在appversion=AppVersion()后打印就是{}
![图片](https://user-images.githubusercontent.com/83632110/203183829-a213e35f-ee1b-4279-ac35-445f752ad4b7.png)

**Comment by HuanLinOTO** [comment]
在appversion = appversion...前打印



在 2022-11-22 08:16:36，"Zichao Lin" ***@***.***> 写道：

在appversion=AppVersion()后打印就是{}

**Comment by earthjasonlin** [comment]
```javascript
log.info("正在获取版本号")
var appversion = AppVersion();
log.info(appversion.data.config);
appversion = appversion.data.config["cg.key_function_controller"].versions[appversion.data.config["cg.key_function_controller"].versions.length-1]

```

**Comment by HuanLinOTO** [comment]
log.info("正在获取版本号")

var appversion = AppVersion();

log.info(appversion.data.config);
console.log(appversion)
appversion = appversion.data.config["cg.key_function_controller"].versions[appversion.data.config["cg.key_function_controller"].versions.length-1]



在 2022-11-22 08:26:19，"Zichao Lin" ***@***.***> 写道：

log.info("正在获取版本号")varappversion=AppVersion();log.info(appversion.data.config);appversion=appversion.data.config["cg.key_function_controller"].versions[appversion.data.config["cg.key_function_controller"].versions.length-1]

**Comment by earthjasonlin** [comment]
```
{
  retcode: 0,
  message: 'OK',
  data: { config: {} },
  StringVersion: '{"retcode":0,"message":"OK","data":{"config":{}}}'
}
```

**Comment by HuanLinOTO** [comment]
???套娃了？？？



在 2022-11-22 08:29:51，"Zichao Lin" ***@***.***> 写道：

{
  retcode: 0,
  message: 'OK',
  data: { config: {} },
  StringVersion: '{"retcode":0,"message":"OK","data":{"config":{}}}'
}

**Comment by HuanLinOTO** [comment]
我自己看看去



在 2022-11-22 08:29:51，"Zichao Lin" ***@***.***> 写道：

{
  retcode: 0,
  message: 'OK',
  data: { config: {} },
  StringVersion: '{"retcode":0,"message":"OK","data":{"config":{}}}'
}

**Comment by HuanLinOTO** [comment]
确实没返回 应该是官方改api了 直接换成3.2.0吧



在 2022-11-22 08:29:51，"Zichao Lin" ***@***.***> 写道：

{
  retcode: 0,
  message: 'OK',
  data: { config: {} },
  StringVersion: '{"retcode":0,"message":"OK","data":{"config":{}}}'
}

**Comment by earthjasonlin** [comment]
改成3.2才行，但是云原神包里唯一一个跟版本号有关系的包是这个
``
GET /ptolemaios/api/getLatestRelease?app_id=1953440998&app_version=3.2.0&channel=appstore

``


我明天试试3.3行不行，如果可以的话就真的没关系了








At 2022-11-22 08:37:23, "HuanLinMaster" ***@***.***> wrote:

确实没返回 应该是官方改api了 直接换成3.2.0吧



在 2022-11-22 08:29:51，"Zichao Lin" ***@***.***> 写道：

{
retcode: 0,
message: 'OK',
data: { config: {} },
StringVersion: '{"retcode":0,"message":"OK","data":{"config":{}}}'
}
